local:
  idp_cert_fingerprint: "9E:65:2E:03:06:8D:80:F2:86:C7:6C:77:A1:D9:14:97:0A:4D:F4:4D"  
  
development:
  assertion_consumer_service_url: "http://myfitorbit.dev/saml/consume"
  issuer: "http://myfitorbit.dev"
  idp_cert_fingerprint: "05:AF:2D:72:4F:0D:5E:E9:2D:49:E8:4F:DC:19:5D:6C:43:67:25:47"

myfitorbitqa:
  assertion_consumer_service_url: "https://qa1.myfitorbit.com/saml/consume"
  issuer: "http://qa1.myfitorbit.com"
  idp_cert_fingerprint: "05:AF:2D:72:4F:0D:5E:E9:2D:49:E8:4F:DC:19:5D:6C:43:67:25:47"

myfitorbitprod:
  assertion_consumer_service_url: "https://www.myfitorbit.com/saml/consume"
  issuer: "http://www.myfitorbit.com"
  idp_cert_fingerprint: "2C:66:9E:A3:ED:36:4B:EA:9F:D9:84:0A:A0:7C:B8:56:BF:A1:E0:53"
